In [23]:
import numpy as np
a = np.array([[1, 6],
              [2, 8], 
              [3, 11], 
              [3, 10], 
              [1, 7]])

In [24]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [25]:
a.shape

(5, 2)

In [26]:
a.mean(axis = 0)

array([2. , 8.4])

In [27]:
mean_a = np.mean(a, axis = 0)
print(mean_a)

[2.  8.4]


In [28]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [29]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
print(a_centered_sp)

8.0


In [30]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0